services:
  postgres:
    image: postgres:16.2
    container_name: roky_postgres
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=roky-db
    ports:
      - '5433:5432'
    restart: unless-stopped
    volumes:
     - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      PGADMIN_DEFAULT_EMAIL: lpezo777@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_LISTEN_PORT: 8090
    expose:
      - 8090
    depends_on:
      - postgres
    volumes:
      - data-pgadmin:/var/lib/pgadmin

  server:
    container_name: electric-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/roky-db
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres

volumes:
  postgres_data:
  data-pgadmin:
